development:
  host: 127.0.0.1
  database: doandose_development
  raise_not_found_error: false

test:
  host: 127.0.0.1
  database: doandose_test
  raise_not_found_error: false

staging:
  host: 127.0.0.1
  database: doandose_production
  raise_not_found_error: false

production:
  host: 127.0.0.1
  database: doandose_production
  raise_not_found_error: false