production:
  social:
    twitter:
      key: Gymvj9mbv9MARcFga1ffQw
      secret: nm8pS8DRKttbqmQDvJwN790gwla96DKoyRzKIS0uRQI
    google:
      key: 419731615326.apps.googleusercontent.com
      secret: TYqSi86OuJqMmVVJpmIFvM4v
    facebook:
      key: 197324647062694
      secret: 2691848d75f50949d8fce873cc6261d8
    identity: