production:
  social:
    twitter:
      key: Gymvj9mbv9MARcFga1ffQw
      secret: nm8pS8DRKttbqmQDvJwN790gwla96DKoyRzKIS0uRQI
    google:
      key: 419731615326.apps.googleusercontent.com
      secret: TYqSi86OuJqMmVVJpmIFvM4v
    facebook:
      key: 197324647062694
      secret: 2691848d75f50949d8fce873cc6261d8

  mandrill_api_key: 3e4b0875-73c5-40b7-b32f-3b7aefbd834a
  domain: 'http://www.doando.se/'
  mail:
    delivery_method: smtp
    address: smtp.gmail.com
    port: 587
    authentication: plain
    username: dev@doando.se
    password: pedraroxa
    enable_starttls_auto: true